  version: '3.8'

  services:
    mysqldb:
      image: mysql:latest
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=EC2024_08
      ports:
        - 3306:3306
      volumes:
        - db:/var/lib/mysql
    bakery-app:
      volumes:
      - ./src:/src
      depends_on:
        - mysqldb
      build: ./src
      restart: always
      ports:
        - 3000:3000
      environment:
        - DB_HOST=localhost
        - DB_USER=root
        - DB_PASSWORD=root
        - DB_NAME=bakery
      stdin_open: true
      tty: true

  volumes: 
    db: